export const INVITE_CODE_ALPHABET = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
export const INVITE_CODE_PREFIX = "KUTU";
export const INVITE_CODE_SUFFIX_LENGTH = 4;

export const REFERENCE_ALPHABET = "0123456789";

export const OTP_VERIFY_RATE_LIMIT_PER_PHONE = 10;
export const OTP_VERIFY_RATE_LIMIT_WINDOW_MINUTES = 10;
